- app/helpers/admin/menus_helper.rb
Fix admin: left menus and breadcrumb
> Fix admin: left menus and breadcrumb

- app/helpers/admin/menus_helper.rb
(Update) Fix admin: left menus and breadcrum #29
> (Update) Fix admin: left menus and breadcrum

- app/assets/javascripts/admin/custom_fields.js
> Custom fields tinymce language should be the current locale

- app/views/layouts/admin.html.erb
- app/views/layouts/admin/_sidebar.html.erb
> Moves sidebar profile information to dropdown

- app/assets/javascripts/admin/core.js
- app/assets/javascripts/admin/elfinder/upload_elfinder.js
- app/decorators/user_decorator.rb
- app/helpers/uploader_helper.rb
- app/models/term_taxonomy.rb
- app/views/admin/comments/reply.html.erb
- app/views/admin/users/profile_edit.html.erb
- fix url avatar user and add function: url_to_file_path
- add validate input text only latin letters	
- fix comments: button spam status	
- add attr_accessible user_id in term_taxonomy
- fix elfinder: Preview after upload file
> Fix various

- app/controllers/admin_controller.rb
- app/helpers/admin/menus_helper.rb
- app/views/admin/user_roles/form.html.erb
- config/locales/admin/en.yml
- config/locales/admin/es.yml
- config/locales/admin/it.yml
* Fixes dashboard typo
* Changes contents_type to use post_type translation
> Content Types -> Post Type

- app/views/admin/sessions/register.html.erb
This change help to append more elements into user_register_form hooks using the f variable.
> Add form_for f variable to user_register_form

- app/controllers/api/v1/page_controller.rb
- app/controllers/api/v1/post_controller.rb
- config/routes.rb
Simple methods to list pages and posts.
> Page and Post api controllers added

- app/controllers/admin/users_controller.rb
- app/views/admin/users/form.html.erb
user_edit: before render the user edit view
user_after_edited: after user is edited
Now the more actions blocks are within the form.
> Two hooks more

- app/views/admin/users/form.html.erb
I have created a new hook for user_update_more_actions.
Now exists two hooks:
- **user_update_more_actions_form**: for add more actions into the user form
- **user_update_more_actions**: for add more actions outside the user form
> New hook to more actions outside the user form

- app/controllers/admin/sessions_controller.rb
- app/models/site.rb
- app/views/admin/sessions/register.html.erb
- app/views/admin/settings/site.html.erb
- config/locales/admin/en.yml
- config/locales/admin/es.yml
See: https://github.com/owen2345/camaleon-cms/pull/99
> Captcha enable/disable on user registration.

- app/assets/javascripts/admin/modal.js
> Change nil to null

- app/controllers/api/api_controller.rb
- app/helpers/session_helper.rb
Unify current_user removing current_resource_owner
Solved bug with login_user_with_password
> Unify current_user - Api login bug fixed

- app/controllers/api/api_controller.rb
Now ApiController inherit of CamaleonController.
And it have two generic methods more (render_json_error and render_json_ok).
> Added generic API response methods, render_json_error & render_json_ok

- app/views/layouts/admin/_footer.html.erb
I added a space between the word "Version" and the number.
Only style upgrade ;)
> Version number space

- app/views/default_theme/layouts/index.html.erb
- lib/generators/ctheme_template/app/apps/themes/my_theme/views/layouts/index.html.erb
> Fixes css theme link tag in theme generator

- app/apps/plugins/contact_form/admin_forms_controller.rb
- app/apps/plugins/contact_form/contact_form_helper.rb
- app/apps/plugins/contact_form/front_controller.rb
- app/controllers/api/api_controller.rb
- app/controllers/api/v1/contact_form_controller.rb
- config/routes.rb
Two api methods more:
- Get contact form data from slug
- Post new contact form
> Prepare contact_form to use Api methods.

- app/controllers/api/v1/category_controller.rb
- app/serializers/api/base_serializer.rb
- app/serializers/api/v1/category_serializer.rb
- camaleon_cms.gemspec
Added active_model_serializers gem to permit serialize the api response objects
> Api with active_model_serializers

- lib/camaleon_cms/engine.rb
ActiveModel::ArraySerializer error.
Thanks @pulkit21 ;) https://github.com/owen2345/camaleon-cms/pull/190
> ActiveModel::ArraySerializer error fixed

- app/controllers/camaleon_cms/admin/sessions_controller.rb
- app/helpers/camaleon_cms/session_helper.rb
Extract register_user to session_helper.rb to prepare for user api methods.
> Extract register_user

- app/models/camaleon_cms/site.rb
- lib/camaleon_cms/engine.rb
Console initialize message update to camaleon_cms v2
> Site save security_captcha_user_register don't save it.

- app/helpers/camaleon_cms/session_helper.rb
- app/models/camaleon_cms/ability.rb
Adding Namespaces to "@current_user" and User.new to avoid conflicts with other implementations
I found these issues when I started testing the integration with the project that im working on.
> Adding missing namespaces

- app/controllers/camaleon_cms/admin/sessions_controller.rb
I have changed the route using cama_ prefix
> Route error admin_login_path

- app/assets/stylesheets/camaleon_cms/admin/uploader/_uploadfile.css.scss
- app/views/camaleon_cms/admin/media/index.html.erb
> Media style updated

- app/decorators/camaleon_cms/custom_field_decorator.rb
- app/helpers/camaleon_cms/html_helper.rb
- app/views/camaleon_cms/default_theme/partials/_render_custom_field.html.erb
Fixed this issue: https://github.com/owen2345/camaleon-ecommerce/issues/13
> cama_print_i18n_value method added to evaluate i18n attributes. 

- config/locales/camaleon_cms/admin/nl.yml
- config/locales/nl.yml
- config/system.json
I added a complete dutch translation
> added complete dutch locale

- config/locales/camaleon_cms/admin/ru.yml
- config/locales/camaleon_cms/common.yml
- config/locales/camaleon_cms/routes.yml
I don't know how to enable this new added language to admin panel. When I launched there were no radio button that allows me to choose russian language for Admin panel. 
@owen2345 how can I make it visible in admin => settings section?
> Added russian language YAML file for admin panel

- app/helpers/camaleon_cms/email_helper.rb
Including user in extra_data to permit customize the email better.
> Prepare reset password to api methods

- app/models/concerns/camaleon_cms/metas.rb
As discussed in [#320](https://github.com/owen2345/camaleon-cms/pull/320)
> Cleaning useless code

- app/assets/javascripts/camaleon_cms/admin/uploader/_media_manager.js.coffee
- app/controllers/camaleon_cms/admin/media_controller.rb
- app/helpers/camaleon_cms/uploader_helper.rb
- app/views/camaleon_cms/admin/media/_files_list.html.erb
- app/views/camaleon_cms/admin/media/index.html.erb
- config/routes/admin.rb
WIP: Adds media search
The sidebar isn't showing on the search page
> Add media search

- app/controllers/camaleon_cms/admin/posts_controller.rb
- app/controllers/camaleon_cms/admin_controller.rb
- app/controllers/camaleon_cms/frontend_controller.rb
Changes search on titles and content to be case insensitive
> Change searches to be case insensitive

- app/models/camaleon_cms/custom_field_group.rb
- app/views/camaleon_cms/admin/appearances/nav_menus/_custom_fields.html.erb
* Fixes incorrect usage of present?
* Fixes nav menu custom fields template to not render nav menu custom fields when custom fields are not setup for the menu
> Custom fields bugs

- .gitignore
- app/assets/javascripts/camaleon_cms/admin/jquery.validate.js
- app/controllers/camaleon_cms/admin/appearances/nav_menus_controller.rb
- app/helpers/camaleon_cms/frontend/nav_menu_helper.rb
- app/views/camaleon_cms/admin/appearances/nav_menus/_menu_items.html.erb
- app/views/camaleon_cms/admin/appearances/nav_menus/_menu_items_list.html.erb
- lib/camaleon_cms/version.rb
- Navigation menu sort problems
- File extension rules issue
> I fixed some issues that I see.

- app/helpers/camaleon_cms/theme_helper.rb
corrected the comment for proper asset path
> Corrected comment for theme_asset_path

- app/apps/plugins/front_cache/front_cache_helper.rb
To enable more advanced matching. Something like `'/ships/.+/deckplans'`
> Enable matching paths as regexes.

- app/models/concerns/camaleon_cms/custom_fields_read.rb
Raise an exception when trying to set a custom field value for which …
…there is no custom field
No code calling this method checks the return value, hence
returning false makes for a silent failure
> Custom fields diagnostics

- app/models/camaleon_cms/plugin.rb
- app/models/camaleon_cms/theme.rb
- app/models/concerns/camaleon_cms/custom_fields_read.rb
- app/models/concerns/camaleon_cms/metas.rb
This is the conflict-free part of #392.
> just make models more readable

- app/controllers/camaleon_cms/admin/sessions_controller.rb
- app/decorators/camaleon_cms/site_decorator.rb
- app/helpers/camaleon_cms/session_helper.rb
- app/models/concerns/camaleon_cms/user_methods.rb
Also treat both username and email case insensitively when validating uniqueness
> Treat username case insensitively when logging in

- app/helpers/camaleon_cms/session_helper.rb
In test environment request.user_agent is nil but
c[2] is "", hence sessions are not functioning.
Convert request.user_agent to string to fix this.
>  Fix user agent check to work in test environment. 

- app/models/camaleon_cms/ability.rb
- app/models/camaleon_cms/category.rb
- app/models/camaleon_cms/custom_field.rb
- app/models/camaleon_cms/custom_field_group.rb
- app/models/camaleon_cms/custom_fields_relationship.rb
- app/models/camaleon_cms/nav_menu.rb
- app/models/camaleon_cms/nav_menu_item.rb
- app/models/camaleon_cms/plugin.rb
- app/models/camaleon_cms/post.rb
- app/models/camaleon_cms/post_comment.rb
- app/models/camaleon_cms/post_default.rb
- app/models/camaleon_cms/post_relationship.rb
- app/models/camaleon_cms/post_tag.rb
- app/models/camaleon_cms/post_type.rb
- app/models/camaleon_cms/site.rb
- app/models/camaleon_cms/term_relationship.rb
- app/models/camaleon_cms/term_taxonomy.rb
- app/models/camaleon_cms/theme.rb
- app/models/camaleon_cms/user.rb
- app/models/camaleon_cms/user_relationship.rb
- app/models/camaleon_cms/user_role.rb
- app/models/camaleon_cms/widget/assigned.rb
- app/models/camaleon_cms/widget/main.rb
- app/models/camaleon_cms/widget/sidebar.rb
- app/models/concerns/camaleon_cms/categories_tags_for_posts.rb
- app/models/concerns/camaleon_cms/custom_fields_read.rb
- app/models/concerns/camaleon_cms/metas.rb
- app/models/concerns/camaleon_cms/site_default_settings.rb
- app/models/concerns/camaleon_cms/user_methods.rb
Reverts owen2345/camaleon-cms#522 (many errors)
> Revert "code cleanup in models"

- app/models/camaleon_cms/ability.rb
- remove use of Object#to_s in interpolation
- add spaces
> cleanup and improvements in ability class

- config/locales/camaleon_cms/common.yml
Hey guys,
in my last PR for German translation I totally forgot to translate the `common.yml`. Here it is.
> German translation - complement

- config/locales/camaleon_cms/admin/js.yml
In Rails, the locale code ‘zh-CN’ it usually refers to simplified Chinese
Reference: https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale
> Revised simplified Chinese translation

- app/helpers/camaleon_cms/admin/application_helper.rb
- app/views/camaleon_cms/admin/categories/index.html.erb
- app/views/camaleon_cms/admin/posts/index.html.erb
- config/locales/camaleon_cms/admin/en.yml
- config/locales/camaleon_cms/admin/es.yml
- config/locales/camaleon_cms/admin/fr.yml
- config/locales/camaleon_cms/admin/it.yml
- config/locales/camaleon_cms/admin/nl.yml
- config/locales/camaleon_cms/admin/pt-BR.yml
- config/locales/camaleon_cms/admin/pt.yml
- config/locales/camaleon_cms/admin/ru.yml
- config/locales/camaleon_cms/admin/zh-CH.yml
In Rails, the automatic pluralizes apply only to English.
> Removed some automatic pluralizes

- README.md
- camaleon_cms.gemspec
- spec/dummy/.gitignore
- spec/features/pages_spec.rb
- spec/features/posts_spec.rb
- spec/spec_helper.rb
- spec/support/common.rb
Just wait while `TinyMCE` initialized
> Fix test cases

- config/routes/frontend.rb
> Fix frontend routes issues

- lib/generators/camaleon_cms/gem_plugin_generator.rb
Using relative paths to specify gem plugins
> Improve gem plugin generator

- app/assets/stylesheets/camaleon_cms/admin/uploader/_uploadfile.css.scss
> Improve media manager style

- lib/ext/string.rb
- spec/dummy/.gitignore
```
'图片'.parameterize # will return ''
```
> Sanitize the filename of uploaded file

- lib/plugin_routes.rb
Accumulates strings on every request
> memory leak in plugin routes

- app/apps/plugins/front_cache/front_cache_helper.rb
Apologies, but there was a bug in my previous PR. The methods to read the cache were not checking the same paths as the method to write the cache, so nothing was being read from cache.
> fix paths in cache methods

- app/uploaders/camaleon_cms_local_uploader.rb
Not sure how this got into master
> fix method to delete folders

- app/controllers/camaleon_cms/admin/sessions_controller.rb
- app/controllers/camaleon_cms/frontend_controller.rb
close https://github.com/owen2345/camaleon-cms/issues/612
> Remove outdated data in the session

- app/views/camaleon_cms/admin/settings/custom_fields/form.html.erb
fix for issue https://github.com/owen2345/camaleon-cms/issues/704
> use custom user model name if it present

- app/assets/javascripts/camaleon_cms/admin/admin-manifest.js
>  Re #740 modify admin-manifest file

- app/assets/javascripts/camaleon_cms/admin/_post.js
> fix typo error

- app/controllers/camaleon_cms/admin/media_controller.rb
- app/helpers/camaleon_cms/uploader_helper.rb
> Slugify folder name when creating

- app/helpers/camaleon_cms/admin/application_helper.rb
fix bug when pages area longer than 6 column
> update will_paginate column distribution

- app/uploaders/camaleon_cms_aws_uploader.rb
When I submitted the PR to fix thumbnails on SVGs, I left out the AWS uploader by accident. With this PR the thumbnails will work on AWS uploads.
> fix SVG thumbs on AWS

- app/views/camaleon_cms/admin/posts/index.html.erb
improved usability of the administrative interface
> added post type edit link on post elements list page

- app/controllers/camaleon_cms/admin/settings/post_types_controller.rb
> added create and update post_type hooks

- app/views/camaleon_cms/admin/categories/index.html.erb
sorry, I'm accidentally closed the previous PR
> added parent id data attribute in category list

- app/helpers/camaleon_cms/uploader_helper.rb
> fixed creating uploded image versions

- app/views/camaleon_cms/admin/settings/custom_fields/_get_items.html.erb
Added translatable default value in custom field settings
> Added translatable default value

- app/assets/javascripts/camaleon_cms/admin/uploader/_media_manager.js.coffee
this helps the user to fill in multiple image fields
> added last opened folder in the media manager

- app/assets/javascripts/camaleon_cms/admin/_post.js
- app/assets/javascripts/camaleon_cms/admin/custom_fields_form.js
- app/controllers/camaleon_cms/admin/settings/custom_fields_controller.rb
- app/models/concerns/camaleon_cms/custom_fields_read.rb
- app/views/camaleon_cms/admin/posts/_sidebar.html.erb
- app/views/camaleon_cms/admin/settings/custom_fields/_render_category_simple.html.erb
- app/views/camaleon_cms/admin/settings/custom_fields/form.html.erb
- config/routes/admin.rb
Added the ability to create groups of custom fields for posts belonging to the same category. Fields groups for posts in parent categories are inherited for children. #
> Custom fields groups of custom fields for posts belonging to the same category.

- app/assets/javascripts/camaleon_cms/admin/_data.js
for the convenience of the content manager
> added fix_list_elements parameter for TinyMCE

- app/assets/stylesheets/camaleon_cms/admin/lte/_admin.css.scss
now the logo looks like this https://i.imgur.com/zgjEmX5.png[https://i.imgur.com/zgjEmX5.png](url)
> fix login page logo

- app/controllers/camaleon_cms/admin/posts_controller.rb
since it (can) show on the final url of the page it becomes very handy
> Ability to search for a post by it's slug

- README.md
- docs/example_gemfile.rb
To lower the barrier of entry for usage and contributions to plugin and theme development
> Support Plugin / Theme usage and development

- app/assets/javascripts/camaleon_cms/admin/_custom_fields.js
- app/views/camaleon_cms/admin/settings/custom_fields/fields/_image.html.erb
added button to delete the image because if the image has a version, it is impossible to delete the image
> image custom field remove button

- app/uploaders/camaleon_cms_aws_uploader.rb
Reverts owen2345/camaleon-cms#872
> Revert "fixed S3 bucket options merge error"

- app/controllers/camaleon_cms/admin_controller.rb
I know this doesn't add much value to your project but you could use the implicit return to assign this value.
http://alanwsmith.com/assigning-ruby-variables-with-a-case-statement
https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/ConditionalAssignment
> Use implicit return on case statement assignment

- .gitignore
- lib/camaleon_cms/engine.rb
- lib/plugin_routes.rb
> Set config.belongs_to_required_by_default = false for Rails 6

- lib/plugin_routes.rb
added https protocol if rails force ssl enabled
> add https to default url options

- config/routes/admin.rb
- spec/features/admin/not_found_spec.rb
> Fix admin error path

- .travis.yml
- Gemfile
- app/helpers/camaleon_cms/camaleon_helper.rb
- app/helpers/camaleon_cms/short_code_helper.rb
- app/helpers/camaleon_cms/uploader_helper.rb
- app/models/camaleon_cms/post.rb
- app/models/concerns/camaleon_cms/user_methods.rb
- camaleon_cms.gemspec
- lib/plugin_routes.rb
- spec/dummy/config/application.rb
Fixes #950, #951, #952. No functional changes, just fixes for deprecation messages.
> Rails 6 1 deprecations

- app/helpers/camaleon_cms/frontend/site_helper.rb
See the newer method here - https://github.com/owen2345/camaleon-cms/blob/master/app/helpers/camaleon_cms/frontend/site_helper.rb#L55
> Remove redundant `is_profile` method - there is a newer one

- app/models/camaleon_cms/ability.rb
- app/models/camaleon_cms/category.rb
- app/models/camaleon_cms/custom_field.rb
- app/models/camaleon_cms/custom_field_group.rb
- app/models/camaleon_cms/custom_fields_relationship.rb
- app/models/camaleon_cms/media.rb
- app/models/camaleon_cms/meta.rb
- app/models/camaleon_cms/nav_menu.rb
- app/models/camaleon_cms/nav_menu_item.rb
- app/models/camaleon_cms/plugin.rb
- app/models/camaleon_cms/post.rb
- app/models/camaleon_cms/post_comment.rb
- app/models/camaleon_cms/post_default.rb
- app/models/camaleon_cms/post_relationship.rb
- app/models/camaleon_cms/post_tag.rb
- app/models/camaleon_cms/post_type.rb
- app/models/camaleon_cms/site.rb
- app/models/camaleon_cms/term_relationship.rb
- app/models/camaleon_cms/term_taxonomy.rb
- app/models/camaleon_cms/theme.rb
- app/models/camaleon_cms/user.rb
- app/models/camaleon_cms/user_role.rb
- app/models/camaleon_cms/widget/assigned.rb
- app/models/camaleon_cms/widget/main.rb
- app/models/camaleon_cms/widget/sidebar.rb
- app/validators/camaleon_cms/post_uniq_validator.rb
- app/validators/camaleon_cms/uniq_validator.rb
Fixes https://github.com/owen2345/camaleon-cms/issues/491
> Gave some love to models - fixed association naming, namespacing, etc.

- app/assets/javascripts/camaleon_cms/admin/lte/app.js
- app/assets/stylesheets/camaleon_cms/admin/lte/_admin.css.scss
- app/assets/stylesheets/camaleon_cms/admin/lte/skins/skin-black-light.css
- app/assets/stylesheets/camaleon_cms/admin/lte/skins/skin-black.css
- app/assets/stylesheets/camaleon_cms/admin/lte/skins/skin-blue-light.css
- app/assets/stylesheets/camaleon_cms/admin/lte/skins/skin-blue.css
- app/assets/stylesheets/camaleon_cms/admin/lte/skins/skin-green-light.css
- app/assets/stylesheets/camaleon_cms/admin/lte/skins/skin-green.css
- app/assets/stylesheets/camaleon_cms/admin/lte/skins/skin-purple-light.css
- app/assets/stylesheets/camaleon_cms/admin/lte/skins/skin-purple.css
- app/assets/stylesheets/camaleon_cms/admin/lte/skins/skin-red-light.css
- app/assets/stylesheets/camaleon_cms/admin/lte/skins/skin-red.css
- app/assets/stylesheets/camaleon_cms/admin/lte/skins/skin-yellow-light.css
- app/assets/stylesheets/camaleon_cms/admin/lte/skins/skin-yellow.css
Has several CSS fixes and doesn't yet require jQuery 3.x
> Bump AdminLTE to 2.3.11
