owen2345/camaleon-cms

app/views/shortcode_templates/widget.html.erb

Widgets should be rendered by default in the current locale, not the full :description database field

Render widgets translated to the current locale

---

config/initializers/rufus_cron.rb

Also removes rescuing `LoadError` when rufus cannot be loaded

Don't rescue generic exception. This will hang the process

---

config/initializers/elfinder.rb

Opening a module more than once in a single file is unnecessary

Elfinder initializer cleanup

---

app/views/admin/users/form.html.erb
config/locales/admin/en.yml
config/locales/admin/es.yml

This new hooks permits add more actions in admin user edit profile for each plugin.

User update more actions hook

---

app/controllers/api/api_controller.rb
app/controllers/api/v1/category_controller.rb
app/helpers/session_helper.rb
camaleon_cms.gemspec
config/initializers/doorkeeper.rb
config/locales/doorkeeper.en.yml
config/routes.rb
db/migrate/20150930115030_doorkeeper_configuration.rb
lib/camaleon_cms/engine.rb

Hi! 
I created a integration with doorkeeper and camaleon-cms (oauth integration).
I added a basic api structure also.
- Related issue: https://github.com/owen2345/camaleon-cms/issues/101
Regards

Doorkeeper integration.

---

app/apps/plugins/contact_form/front_controller.rb

For new email domains terminations (example: .digital)

Allow email domains up to 10 characters in the contact form plugin

---

config/routes/frontend.rb

Example: Random troll writes domain.com/asdasdasd/adfasdasd.
Just changed the regexp to allow '/' in the urls.

Raise error when visiting unexisting urls.

---

app/controllers/api/api_controller.rb
app/controllers/concerns/frontend_concern.rb

Error Stack on heroku:
[3] ! Unable to load application: SyntaxError: /app/vendor/bundle/ruby/2.1.0/gems/camaleon_cms-1.0.8/app/controllers/api/api_controller.rb:10: syntax error, unexpected ':', expecting =>
'userMessage': user_message,
^
/app/vendor/bundle/ruby/2.1.0/gems/camaleon_cms-1.0.8/app/controllers/api/api_controller.rb:11: syntax error, unexpected ':', expecting :: or '[' or '.'
'internalMessage': internal_message,
^
/app/vendor/bundle/ruby/2.1.0/gems/camaleon_cms-1.0.8/app/controllers/api/api_controller.rb:12: syntax error, unexpected ':', expecting :: or '[' or '.'
'code': code
^
/app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require': /app/vendor/bundle/ruby/2.1.0/gems/camaleon_cms-1.0.8/app/controllers/api/api_controller.rb: …

fix syntax api_controller for Heroku

---

app/views/default_theme/sitemap.xml.builder

The current updated_at yields something like: `2015-11-01 13:46:22 UTC` which Google doesn't consider valid.
Adding to_date makes it valid.

fix lastmod date format in sitemap.xml.builder to be Google-compliant

---

app/helpers/camaleon_cms/uploader_helper.rb

This PR makes browsing non-trivial s3 directories usable by only parsing the current directory and not alway building the whole tree.
It also reduces the code complexity of the media management.

parse only current fog dir #235

---

app/helpers/camaleon_cms/frontend/site_helper.rb
app/helpers/camaleon_cms/html_helper.rb

Create pre_assets_content to insert script code before load js libraries in the head of the website.
Used in google analytics plugin to permit include ga code before execute the google analytics constructor code.

pre_assets_content

---

app/apps/themes/new/custom_helper.rb
lib/generators/camaleon_cms/theme_template/app/apps/themes/my_theme/main_helper.rb
lib/generators/camaleon_cms/theme_template/app/apps/themes/my_theme/views/layouts/index.html.erb

If user switches away from the Clean Theme, and later re-selects it, a duplicate entry for Main Menu is created. This fix prevents that from happening.

Fix Clean Theme to avoid creating duplicate main_menu

---

app/helpers/camaleon_cms/frontend/nav_menu_helper.rb

In order to use draw_menu with angularJS, attributes must be added to the item container.
Ex: 
`callback_item: lambda{|args| args[:item_container_attrs] = "ui-sref-active='active'"; args[:link_attrs] = "ui-sref=\"category({categoryId: #{args[:menu_item][:id]}, categorySlug: '#{args[:menu_item][:slug]}'})\" href"}`

added item_container_attrs when drawing menus

---

app/models/concerns/camaleon_cms/metas.rb

When using eager_load metas are preloaded, so it's quicker to browse the array instead of sending a new SQL request.

optimized get_meta when using eager_load

---

app/views/camaleon_cms/admin/appearances/nav_menus/_custom_fields.html.erb

Simply removed the extra 'camaleon_cms' in the path, and it works for me now.

fixes call to partial custom_fields/render

---

app/models/camaleon_cms/post.rb

Using camaleon-post-order-plugin is possible that you have multiple post with the same post_order.

Include created_at order by default

---

app/models/concerns/camaleon_cms/metas.rb

When I call gem_meta(:symbol_key) the method always response with empty value (eql?)

Verify if the key on get_meta is a Symbol before compare

---

app/helpers/camaleon_cms/uploader_helper.rb
lib/tasks/camaleon_cms/camaleon_tasks.rake

WIP
camaleon 2.0 changes the thumbnail names. The thumbnails need to regenerated with the correct name.
* Splits out thumbnail generation
* Creates a rake task to generate thumbnails

Add task to generate thumbnails

---

app/apps/plugins/front_cache/admin_controller.rb
app/apps/plugins/front_cache/views/admin/settings.html.erb

Frontcache settings page was returning error on first load because `@caches[:paths]` was nil.
`bootstrap-select.js` library is included into main.js now so there is no need for explicit include. And actually it does not work because file name is `_bootstrap-select.js` (not `bootstrap-select.js`)

Frontcache plugin

---

app/models/camaleon_cms/ability.rb

When a dynamic role is created without any power of editing 'other permissions' (those checkboxes in create role screen) @roles_manager returns nil in ability.rb. 
Because of this nil return the method .each fails and raises an error. I believe it's now fixed by using the try before each.

Added fix to ability iteration

---

app/models/concerns/camaleon_cms/custom_fields_read.rb

input datas structure has changed.
it was   {"0"=>{ "untitled-text-box"=>{"id"=>"262",
"values"=>{"0"=>"33333"}}} }
now it is : { "untitled-text-box"=>{"id"=>"262",
"values"=>{"0"=>"33333"}}}

Bugfix set_field_values

---

app/controllers/camaleon_cms/frontend_controller.rb
app/helpers/camaleon_cms/frontend/application_helper.rb
app/helpers/camaleon_cms/frontend/content_select_helper.rb

The concept of this helper is what I see in wordpress they can select content by
```
<?php while (have_posts()) : the_post(); ?>
<h2 id="post-<?php the_ID(); ?>">
<a href="<?php the_permalink() ?>" rel="bookmark" title="Permanent Link to <?php t he_title_attribute(); ?>">
<?php the_title(); ?>
</a></h2>
<?php endwhile; ?>
```
So what I want to she in camaleon is 
```
<% each_post_of('post') do %>
<%= image_tag the_thumbnail %>
<%= the_title %>
<%= the_excerpt %>
<% end %>
```
On post page just easy call by
```
<%= the_title %>
<%= the_content %>
```
On post type page easy call by
`<% the_posts %>
`
Post type can simple call by
`the_post_type('page')`
Post can simple select by
```
the_post_type('page') do
the_post('about')
end
```
Custom field is better call by
```
the_post('about') do …
```

select content helper

---

camaleon_cms.gemspec

Without this `bundle exec rspec` produces:
<pre>
Gem::LoadError: rspec-core is not part of the bundle. Add it to Gemfile.
</pre>

Indicate development dependencies on rspec and capybara

---

app/helpers/camaleon_cms/session_helper.rb

Rescuing nil hides all kinds of errors, such as doorkeeper_token
not being defined. This subsequently causes strange failures
downstream, like current_user being nil in some parts of the code
when a user session is clearly present at controller level.

Do not rescue nil in session helper

---

app/helpers/camaleon_cms/hooks_helper.rb

This changes conditionals from postfix to prefix form to make the logic a little clearer.

Move conditionals for clarity

---

app/helpers/camaleon_cms/session_helper.rb

This is still hacky but at least the dependency on doorkeeper_token is explicitly stated and checked.
With this change admin area works again.

Second fix for doorkeeper_token/rescue nil

---

app/helpers/camaleon_cms/session_helper.rb

`respond_to?(:doorkeeper_token)` is always false even though the method is there, hence try calling it and rescue `NameError` instead

Take 3 at doorkeeper_token fix.

---

app/mailers/camaleon_cms/html_mailer.rb

This adds a second email hook to permit modifying email parameters just before the email is about to be sent. It is needed to make camaleon mandrill plugin work again with the latest camaleon cms version (https://github.com/raulanatol/camaleon-mandrill-plugin/pull/2 for the plugin change).

email_late hook, to permit modifying e.g. smtp settings

---

app/models/concerns/camaleon_cms/user_methods.rb
spec/models/user_spec.rb
spec/spec_helper.rb

Email addresses are case insensitive, however camaleon-cms allowed different case versions of the same email addresses to exist. This PR lowercases email addresses before validation.
I have not looked into usernames yet or whether it is possible to log in by specifying the email address in a different case from what is stored in the database (e.g. all caps).

Lowercase user email addresses

---

app/assets/javascripts/camaleon_cms/admin/_custom_fields.js
app/views/camaleon_cms/admin/settings/custom_fields/fields/_checkbox.html.erb

Checkboxes are checked by setting the checked attribute to true/false,
not by manipulating value. Previously checkbox custom fields would
always be checked, regardless of actual state of the field; with
this change, the checkbox custom fields are behaving correctly.

Fix checkbox custom fields always being checked in admin

---

app/models/camaleon_cms/ability.rb
app/models/camaleon_cms/category.rb
app/models/camaleon_cms/custom_field.rb
app/models/camaleon_cms/custom_field_group.rb
app/models/camaleon_cms/custom_fields_relationship.rb
app/models/camaleon_cms/nav_menu.rb
app/models/camaleon_cms/nav_menu_item.rb
app/models/camaleon_cms/plugin.rb
app/models/camaleon_cms/post.rb
app/models/camaleon_cms/post_comment.rb
app/models/camaleon_cms/post_default.rb
app/models/camaleon_cms/post_relationship.rb
app/models/camaleon_cms/post_tag.rb
app/models/camaleon_cms/post_type.rb
app/models/camaleon_cms/site.rb
app/models/camaleon_cms/term_relationship.rb
app/models/camaleon_cms/term_taxonomy.rb
app/models/camaleon_cms/theme.rb
app/models/camaleon_cms/user.rb
app/models/camaleon_cms/user_relationship.rb
app/models/camaleon_cms/user_role.rb
app/models/camaleon_cms/widget/assigned.rb
app/models/camaleon_cms/widget/main.rb
app/models/camaleon_cms/widget/sidebar.rb
app/models/concerns/camaleon_cms/categories_tags_for_posts.rb
app/models/concerns/camaleon_cms/custom_fields_read.rb
app/models/concerns/camaleon_cms/metas.rb
app/models/concerns/camaleon_cms/site_default_settings.rb
app/models/concerns/camaleon_cms/user_methods.rb

- Prefer single-quoted strings if string interpolation or special symbols not needed
- Keep a blank line before and after private
- remove redundant self 
- add spaces and order relations, scopes for easier to read
- change `where().first` into `find_by` 
- straigt return in methods without a explicit setting of locale variables
-  change `count != 0` into `any?`

code cleanup in models

---

app/models/camaleon_cms/custom_field.rb
app/models/camaleon_cms/custom_field_group.rb
app/models/camaleon_cms/custom_fields_relationship.rb

- Use single-quoted strings if string interpolation or special symbols are not needed
- Change single line lambda syntax in `-> { }` lambda literal syntax
- Add spaces
- Calls without '.self' to get something
- Keep a blank line before and after private
- Replace `where().first` with `find_by()`
- Array Syntax 
- Remove `.present?` call because is not necessary
- `objectid` is an Integer

Cleanup and improvements in custom fields classes

---

app/models/camaleon_cms/category.rb

- Use single-quoted strings if string interpolation or special symbols are not needed
- Keep a blank line before and after private
- Calls without `self`  to get something
- Add spaces

Cleanup category class

---

app/controllers/camaleon_cms/admin/posts_controller.rb

I don't know how to update the documentation on http://camaleon.tuzitio.com/documentation/category/40758-modules/hooks-1.html though.
I think these are important hooks. If you cache menus for example you need to empty that cache if a post is trashed/restored.

add trash/restore hooks

---

app/uploaders/camaleon_cms_local_uploader.rb

User may delete the files manually for some reason.
Then if user try to delete the file in UI, will cause the system throw exception.

delete file only when it exists

---

app/uploaders/camaleon_cms_uploader.rb

User may fill in such image url: https://unsplash.it/375/333 it will cause `validate_file_format `
throw exception.
I think we should should fix this.
Exception info as below
```
NoMethodError in CamaleonCms::Admin::MediaController#actions
undefined method `downcase' for nil:NilClass
Extracted source (around line #127):
#125     return true if valid_formats == "*" || !valid_formats.present?
#126     valid_formats = valid_formats.gsub(' ', '').downcase.split(',') + get_file_format_extensions(valid_formats).split(',')
*127     valid_formats.include?(File.extname(key).sub(".", "").split('?').first.downcase)
#128   end
#129 
#130 
```

fix invalid key causes validate_file_format throw exception

---

app/controllers/camaleon_cms/admin/appearances/nav_menus_controller.rb

Hey,
I noticed that adding custom menus via hook `nav_menu_custom` is not working. The reason is that the `kind` will be saved as an empty string.
`'' || true # => ''`
`''.present? # => false`

prevent nav menu item field 'kind' to be the empty string

---

config/initializers/assets.rb

When creating a new Camaleon install, one would receive errors when visiting the theme section of the admin control panel because PNG and JPG images were not being compiled. I changed the config/initializers/assets.rb to include PNG and JPG in the file types that it looks for so it will compile properly at this time. Previously, the line 
`Rails.application.config.assets.precompile += %w( themes/*/assets/* )`
was used, however this code segment was swapped for the proc which I adjusted to include those image file types.

Added PNG and JPG file types to asset precompilation.

---

app/controllers/camaleon_cms/admin/posts/drafts_controller.rb
app/controllers/camaleon_cms/admin/posts_controller.rb
app/decorators/camaleon_cms/post_decorator.rb
app/models/camaleon_cms/post.rb
app/views/camaleon_cms/admin/posts/_sidebar.html.erb

Hey, I noticed that the functionality to create drafts and restore them is broken when you also manage the page hierarchy. This is because the `post_parent` field is used for both purposes. The problem is that there is no distinction between a normal draft that is just a post with status 'draft' and child drafts that are basically a copy of the original post and have that original post as their parent.
- Create a post
- Create another post and set the first post as the parent
- Now in the second post click "Save Draft"
- Go to the created draft and restore it. You will get an error "Parent Post Recursive"
The same happens if you set a post's status to 'draft'. When you want to restore that post you get the same error AND that post will be DELETED!!!
So my suggestion is to distinguish …

fix restoring of drafts

---

app/models/concerns/camaleon_cms/custom_fields_read.rb

We were experiencing duplicates in custom fields, presumably a race condition between multiple saves/autosave where content with a large number of custom fields were doing the delete and the same time and then running through and add multiples back in. This whole process is now wrapped in one transaction.

wrap custom fields setter in activerecord transaction

---

app/models/camaleon_cms/post.rb

I'm sorry, in #641 there was something missing. Of course posts with status `draft_child` can have the same slug as their parent. I also made that line a bit shorter.

add draft_child to slug validation

---

app/controllers/camaleon_cms/admin/comments_controller.rb

Visiting the comments after initializing the new project. Getting 
```NoMethodError (undefined method `paginate' for []:Array):```

Fixed NoMethodError undefined method 'paginate' for comments

---

app/views/layouts/camaleon_cms/admin.html.erb

https://github.com/owen2345/camaleon-cms/issues/593
Please help to fix, otherwise I18n_data will always be empty hash.

fix I18n.backend translations

---

app/apps/plugins/attack/attack_helper.rb
app/apps/plugins/front_cache/admin_controller.rb
app/apps/plugins/front_cache/front_cache_helper.rb
app/controllers/camaleon_cms/admin/media_controller.rb

Fixes #624. Replaced the deprecated method throughout the repo, so please check the code in attack_helper.rb and media_controller.rb.

remove deprecated method 'render :text'

---

app/models/concerns/camaleon_cms/user_methods.rb

after configured to use devise following the custom auth tutorial http://camaleon.tuzitio.com/documentation/category/139779-faqs/custom-login.html the system throws an exception when tried to remove an user using the admin panel

fix error when using another model for authentication (ie.: devise)

---

app/models/camaleon_cms/custom_field_group.rb

This is just a quick fix in a specific file, similar errors might be lurking in other places.
Acording to [this post in SO](https://stackoverflow.com/a/34951198)  
> in Rails 5 ActionController::Parameters now returns an Object instead of a Hash
on Object has no map method

Cast parameters to hash to avoid error in rails 5

---

app/apps/plugins/front_cache/admin_controller.rb
app/apps/plugins/front_cache/config/config.json
app/apps/plugins/front_cache/front_cache_helper.rb
app/apps/plugins/front_cache/views/admin/settings.html.erb

What it does:
- Uses the Rails cache store for the Front Cache plugin instead of manually managing files. This benefits users of distributed cache stores like Memcached or Redis.
- Adds a checkbox to settings to allow preserving the cache on restart. This benefits users of Heroku and others using ephemeral file systems.
- Preserves previous behavior (for the most part). The default cache store in Rails is `:file_store`, so anyone who doesn't configure their Rails cache should experience similar performance to the previous implementation. Also, the cache will still be cleaned on restart unless the new option in settings is selected.
- Addresses #609.
- Bumps plugin version to 0.2.
What it doesn't do:
- Translate the new settings option (I don't have the language skills).
- Allow for …

Use Rails cache store in Front Cache plugin

---

app/models/camaleon_cms/custom_field_group.rb

Unsupported function `with_indifferent_access` remotion on custom_field_group model

Fix custom fields group issue on Rails 5.1.1

---

app/controllers/camaleon_cms/frontend_controller.rb

this fix is related to this issue: https://github.com/owen2345/camaleon-cms/issues/655

using content slug instead of id to prevent conflict between multiple sites

---

app/apps/plugins/front_cache/admin_controller.rb
app/apps/plugins/front_cache/config/locales/translation.yml
app/apps/plugins/front_cache/front_cache_helper.rb
app/apps/plugins/front_cache/views/admin/settings.html.erb
config/locales/camaleon_cms/admin/en.yml

Invalidating the cache allows the user to clean the front cache plugin without losing other cache items like fragment caching. This is preferable to deleting the cache when using cache systems that automatically eject keys when the cache is full. The option is off by default to match previous behavior, and because the default Rails cache is FileStore, which does not eject keys.
This is accomplished by placing a counter in the cache paths. When the counter is incremented, the old cache keys will no longer match the new cache paths, so they remain unused until ejected by the cache system.
Other changes:
- Moved the "Preserve cache on restart" option to the bottom of the list, with the new invalidate option below it.
- Added translations for both of the above options.
- Fixed a typo in an …

Add option to invalidate Front Cache rather than deleting it

---

app/controllers/camaleon_cms/admin/settings/post_types_controller.rb
app/views/camaleon_cms/admin/settings/custom_fields/fields/_post_types.html.erb
app/views/camaleon_cms/admin/settings/custom_fields/form.html.erb
app/views/camaleon_cms/admin/settings/post_types/_form.html.erb
config/locales/camaleon_cms/admin/de.yml
config/locales/camaleon_cms/admin/en.yml

This makes it possible to add custom field groups to post_types themselves, not to their posts. The custom field group appears in the post type settings.

Contrib dev

---

app/controllers/camaleon_cms/camaleon_controller.rb

Fixes #682. Currently, the login page is not exempted from the redirect used on an inactive site, rendering the admin dashboard completely inaccessible. This pull request allows access to the login page. If a user with an admin role logs in, they gain site access. If a user logs in with another role, they are logged out with a message that the site is inactive.
I chose this approach because the existing code appeared designed to restrict access to inactive sites to users with an admin role, so this should fix the bug without altering other behavior.
Please note that the bug was experienced and the fix tested with the following options in system.json:
```
"share_sessions": true
"users_share_sites": true
```
The behavior was the consistent in development mode using multiple subdomains …

Allow login to inactive sites

---

app/apps/plugins/attack/attack_helper.rb
app/helpers/camaleon_cms/uploader_helper.rb
app/uploaders/camaleon_cms_aws_uploader.rb
app/uploaders/camaleon_cms_local_uploader.rb

2 Hooks added (`after_upload` and `after_delete`) to support further customization when uploading or deleting a file. 
This can be useful when adding database management or other custom action after these actions ocurr.
Additionally fixed a bug on attack plugin to be able to run `plugin_install('attack')`

Added hooks for media support

---

app/models/camaleon_cms/custom_field_group.rb
app/models/concerns/camaleon_cms/custom_fields_read.rb
app/views/camaleon_cms/default_theme/single.json.jbuilder

Hi @owen2345,
Association fields, field_values and field_groups have a comment marking them as deprecated and to use the custom_fields, custom_field_values and custom_field_groups instead.
This pull request tries to do that. With it in place, it allows us to improve performance in situations like when we use try to use different custom fields for a post or multiple posts
Nevertheless, there are still places where the old association is still being used because it failed the tests.
I'm not sure if nothing else will break with this change.
Thank you,
Filipe

Replaces deprecated fields, field_values and field_groups associations

---

app/views/camaleon_cms/admin/post_tags/_form.html.erb

When creating a post tag in Post Tags index page, the tag would be saved but nothing showed in the list. 
After investigating the SQL generated, I found `parent_id` is empty.

fix post tag created without parent_id bug

---

app/assets/javascripts/camaleon_cms/admin/_post.js

If the title to be created is not digits nor latin character(a-z, A-z), for example Chinese or Japannese, it would fail to generate slug and leave empty. The content would fail to save.
This is somewhat easy to ignore for non-pro users. So I suggest maybe it should generate 5-length random character slug when slugify result is empty

generate random character when slugify empty

---

app/controllers/camaleon_cms/camaleon_controller.rb

Resubmit of #762.
Fixes #742.
When ActionDispatch::Static can't locate a .js file, the request falls through to Rails. Currently, this causes an ActionController::InvalidCrossOriginRequest exception instead of a simple 404.
The simplest fix is to disable the forgery check when requesting a .js file from the /assets/ directory. Any such request that reaches the controller is for a non-existent file and will cause a 404.

Skip forgery check on .js files in /assets

---

app/controllers/camaleon_cms/frontend_controller.rb

Created a new method that renders a custom 404 page, defined by the user, and with the correct status code, in this case the 404 Not Found. Resolves #767

767: Page not found not giving 404 status code

---

app/controllers/camaleon_cms/frontend_controller.rb

Created endpoint for page not found

---

app/helpers/camaleon_cms/uploader_helper.rb

I noticed that the image optimizer I configured was working for AWS uploads, but not local. This commit ensures that local uploads use the settings hash so any modifications done using the `before_upload` hook are preserved.

Fix 'before_upload' hook when uploading to local filesystem

---

app/helpers/camaleon_cms/uploader_helper.rb
app/uploaders/camaleon_cms_local_uploader.rb

MiniMagick complains when using Camaleon's methods to resize & crop SVG images. This PR converts SVG to JPEG when editing to work around the errors.
This means that only the original image is saved as SVG. Thumbnails and other alternate versions are converted to JPEG.
Fixes #787

convert SVGs to JPEG when editing to avoid errors

---

.travis.yml

This PR caches gems on Travis CI so they don't have to be downloaded each time. [More here](https://docs.travis-ci.com/user/caching#Caching-directories-(Bundler%2C-dependencies)).

Cache bundle on Travis CI

---

app/views/layouts/camaleon_cms/admin.html.erb
spec/support/custom_admin.html.erb

Fixes #817 by removing old test workaround that is no longer needed.

Remove TinyMCE test workaround that breaks plugin tests

---

app/controllers/camaleon_cms/admin/posts_controller.rb

While developing a rails app with camaleon_cms I encountered a bug: https://github.com/owen2345/camaleon-cms/issues/866
I guess it occurs only with postgresql, because I wrote a tmp test inside camaleon_cms gem(which uses sqllite in dummy app) and it wasn't failing.
The problem was wrong place of closing parenthesis of postgres function LOWER.
When it was after "?" sign, it was causing exception in PG query runner.
It was the query before fix:
```sql
SELECT COUNT(DISTINCT "cama_posts"."id")
FROM "cama_posts"
LEFT OUTER JOIN "cama_posts" "parents_cama_posts" ON "parents_cama_posts"."id" = "cama_posts"."post_parent"
AND "parents_cama_posts"."post_class" = 'Post'
LEFT OUTER JOIN "cama_term_taxonomy" ON "cama_term_taxonomy"."id" = "cama_posts"."taxonomy_id" AND
"cama_term_taxonomy"."taxonomy" …
```

Fix query builder bug when params[:q] specified

---

camaleon_cms.gemspec

fix dependencies conflict like this:
```
Bundler could not find compatible versions for gem "aws-sdk-core":
In Gemfile:
camaleon_cms was resolved to 2.4.5.10, which depends on
aws-sdk (~> 2) was resolved to 2.0.1.pre, which depends on
aws-sdk-resources (= 2.0.1.pre) was resolved to 2.0.1.pre, which depends on
aws-sdk-core (= 2.0.1)
aws-sdk-s3 was resolved to 1.0.0.rc5, which depends on
aws-sdk-core (= 3.0.0.rc1)
```

changed aws-sdk dependency version for ActiveStorage support

---

app/uploaders/camaleon_cms_aws_uploader.rb

in block in `objectsaws-sdk-s3 (1.30.1) lib/aws-sdk-s3/bucket.rb` I got error `undefined method merge for nil:NilClass`
because the objects method in bucket.rb waiting a hash:
`   def objects(options = {})
batches = Enumerator.new do |y|
options = options.merge(bucket: @name)`

fixed S3 bucket options merge error

---

app/controllers/camaleon_cms/camaleon_controller.rb

I've been getting a few 500 errors when my CDN requests expired theme asset files. This is caused by `CamaleonController#render_error` looking for a template to render instead of just returning a 404 header. This pull request preserves existing behavior for HTML and returns a 404 status for other request types.
This is not the only possible fix. If you'd prefer to only alter behavior for CSS, it can be done like this instead:
```ruby
respond_to do |format|
format.css { head status }
format.any { render "camaleon_cms/#{status}", :status => status }
end
```
But I thought better to make the change for any request type that is not rendering an HTML page.
Yet another option would be to create a blank CSS file in the directory so there's something to render.

Fix 500 errors when missing theme CSS is requested

---

Gemfile
gemfiles/rails_4_2.gemfile
gemfiles/rails_5_0.gemfile
gemfiles/rails_5_1.gemfile
gemfiles/rails_5_2.gemfile

See this Rails issue: https://github.com/rails/rails/issues/35161
Rails is not compatible with sqlite3 version 1.4 (a fix has been made, but it's in Rails 6). This has been causing CI failures.
There are still CI failures related to a separate problem I couldn't figure out, but this gets us nearer to a working build.

Restrict sqlite3 version due to Rails incompatibility

---

app/controllers/camaleon_cms/frontend_controller.rb

Fixes #875. This behavior was fixed in #878 for sites using the default error page, but sites with a custom error page were not calling the method in that PR.

apply fix in #878 when site has a custom error page

---

camaleon_cms.gemspec
gemfiles/rails_6_0.gemfile
gemfiles/rails_edge.gemfile

CanCanCan just released version 3.0. Here's a [summary of the breaking changes](https://medium.com/@coorasse/hello-cancancan-3-0-d6f444312e6f?sk=3503e2e0de742803c2b26eb95dde3dd2#fbe6).
I don't see anything in the code that should break as a result of this update and the tests are passing locally. I added the new version to the CI gemfiles for Rails 6.0 and Rails edge to get test coverage.

Loosen CanCanCan version restriction

---

Gemfile
camaleon_cms.gemspec
gemfiles/rails_4_2.gemfile
gemfiles/rails_5_0.gemfile
gemfiles/rails_5_1.gemfile
gemfiles/rails_5_2.gemfile
gemfiles/rails_6_0.gemfile
gemfiles/rails_edge.gemfile

Remove duplicated `rspec-rails` and `database_cleaner` gems from gemfiles - they are specified in the gemspec.
Restrict `rubocop` to 0.68.x version, because the 0.69 version has no support for Ruby 2.2.x

Remove duplicated gems and restrict Rubocop version.

---

.travis.yml
Gemfile
README.md
gemfiles/rails_4_2.gemfile
gemfiles/rails_6_0.gemfile
lib/camaleon_cms/engine.rb
spec/dummy/config/application.rb
spec/dummy/config/environments/test.rb

Addresses #895 
Rails 6 introduces a new code loader called Zeitwerk. It is incompatible with some of the filenames in Camaleon, but this is fixed by adding `config.autoloader = :classic` to config.application.rb.
However, there is an error in the eager load paths specified by Camaleon as detailed in #895. Fixing this issue makes Camaleon compatible with Rails 6 as long as `config.autoloader = :classic`. I updated the README with these instructions.
Eager loading is now enabled in the test environment. Without that, the tests were passing despite production deployments being completely broken by the eager loading error.
The following testing issues are fixed as well. These are unrelated to the PR, except that they get the build passing again:
- .travis.yml is edited to handle a change in …

Fix eager load

---

app/assets/stylesheets/camaleon_cms/admin/_custom_admin.css.scss
app/views/camaleon_cms/admin/appearances/themes/index.html.erb

The appearance of the card of the theme's in the index page is currently a little ugly and this PR pretend to improve it visually.
It just changes the HTML and CSS file.
1. The theme image is right now a background image of the card and his size is cover to avoid the stretching.
2. The description of the theme is showing when the user puts the mouse above the theme's image.
3. The theme's name is the footer of the card.
_Desktop version:_
_Mobile version:_

improving the theme's card appearance in the index page

---

app/apps/themes/camaleon_first/views/index.html.erb
app/helpers/camaleon_cms/theme_helper.rb

A new install may have no posts/pages in the database. If this is the case, display a basic "Hello World" page. [fixes #911]

Use default page if no other pages exist

---

app/assets/config/camaleon-cms.js
config/initializers/assets.rb
spec/dummy/app/assets/config/manifest.js
spec/dummy/config/initializers/assets.rb

Sprockets 4.0 has removed support of Procs. All the linked assets should be specified now in the app/assets/config/manifest.js file.
Fixes https://github.com/owen2345/camaleon-cms/issues/921

Fixed Sprockets 4.0 using manifest.js

---

Gemfile
README.md
app/apps/plugins/attack/config/custom_models.rb
app/apps/plugins/front_cache/config/initializer.rb
spec/dummy/config/application.rb

Rails 6 comes bundled with a new code loader, Zeitwerk. This loader relies on the convention of filenames matching class names. This PR defines a few empty classes to comply with this convention so that Zeitwerk may be used. Please note that the build will not pass until/unless https://github.com/owen2345/camaleon-cms-seo/pull/8 is merged, since that plugin has its own Zeitwerk compatibility issue. I have run the spec locally and deployed to production using that PR.

Zeitwerk compatibility

---

app/controllers/camaleon_cms/frontend_controller.rb

Fix for the [#925](https://github.com/owen2345/camaleon-cms/issues/925) issue.
On the common site visit, the `current_theme` is instantiated using `current_site.get_theme.decorate` method chain.
If the FrontendController receives the `ccc_theme_preview` param, the current_theme is instantiated from this param's value, but it is not used, because the `current_site.get_theme_slug` is being appended to the `lookup_context.prefixes`.
So, given the correct behaviour of different methods of `current_theme` instantiation, the fix was to append `current_theme.name` instead of `current_site.get_theme_slug`  to the `lookup_context.prefixes`.

Fixed the themes preview error 

---

app/helpers/camaleon_cms/frontend/seo_helper.rb

Reference
https://www.rubydoc.info/gems/meta-tags/1.2.1/MetaTags%2FViewHelper:display_meta_tags
Depends on 
https://github.com/owen2345/camaleon-cms-seo/pull/19

Add canonical option to seo

---

app/helpers/camaleon_cms/uploader_helper.rb

Total underscoring was replacing dashes with underscores (a dash separated date in filename, for example), giving me headache for a month, until I've discovered this fact :D
So I am proposing this PR to translate only spaces to underscores, to not touch dashes.

Fix filename underscoring on uploading

---

camaleon_cms.gemspec
config/initializers/non_digest_assets.rb

This is for fixing https://github.com/owen2345/camaleon-cms/issues/967
There was a [large discussion on rails-sprockets regarding the non-digest assets](https://github.com/rails/sprockets-rails/issues/49) and [many solutions have been proposed](https://github.com/rails/sprockets-rails#but-what-if-i-want-sprockets-to-generate-non-digest-assets)
Using the `non-digest-assets` gem seems to be the most correct and easy, also not affecting application's performance. I have tested it on production and it is working OK.

Use non-digest-assets gem for using 3rd party assets

---

.travis.yml
app/models/camaleon_cms/post_type.rb
gemfiles/rails_6_1.gemfile
spec/dummy/config/application.rb

Fixes #977 
This PR is basic Rails 6.1 support. There were a couple of changes necessary.
First, instead of requiring all Rails frameworks in the dummy app, only the necessary frameworks are required. This is because Rails started raising some errors when it couldn't locate config for Active Storage, which Camaleon doesn't use anyway.
Second, there is a change to one of the model associations in post_type.rb. Apparently the `:source` option is only valid if there is also a `:through` option, and Rails 6.1 raises an exception on what was previously a no-op. I removed the option (since it apparently didn't do anything anyway), but I wonder if maybe that relationship should be scoped? Please check this part carefully before merging. See the issue linked above for more info.

Rails 6.1 support

---

docs/example_gemfile.rb
lib/generators/camaleon_cms/install_generator.rb

This is fixing a issue when Dependabot running bundler couldn't require `plugin_routes`

Fix requiring plugin_routes in the Gemfile

---

app/views/camaleon_cms/admin/settings/_seo_settings.html.erb
config/locales/camaleon_cms/admin/ar.yml
config/locales/camaleon_cms/admin/de.yml
config/locales/camaleon_cms/admin/en.yml
config/locales/camaleon_cms/admin/es.yml
config/locales/camaleon_cms/admin/fr.yml
config/locales/camaleon_cms/admin/it.yml
config/locales/camaleon_cms/admin/nl.yml
config/locales/camaleon_cms/admin/pt-BR.yml
config/locales/camaleon_cms/admin/pt.yml
config/locales/camaleon_cms/admin/ru.yml
config/locales/camaleon_cms/admin/uk.yml
config/locales/camaleon_cms/admin/zh-CH.yml

`seo_canonical` option has been introduced in this commit https://github.com/owen2345/camaleon-cms/commit/53d016d5253bc037e7b280d55239f99ea02015fb, but there was no Admin UI for setting it.
Added `text_field` for `seo_canonical` option on the `General Site` -> `Seo Settings` tab and translations for the `seo_canonical` key.

Canonical URL field in General Site -> Seo Settings tab

---

app/models/camaleon_cms/category.rb
app/models/camaleon_cms/custom_field.rb
app/models/camaleon_cms/custom_field_group.rb
app/models/camaleon_cms/custom_fields_relationship.rb
app/models/camaleon_cms/media.rb
app/models/camaleon_cms/nav_menu.rb
app/models/camaleon_cms/nav_menu_item.rb
app/models/camaleon_cms/plugin.rb
app/models/camaleon_cms/post.rb
app/models/camaleon_cms/post_comment.rb
app/models/camaleon_cms/post_relationship.rb
app/models/camaleon_cms/post_tag.rb
app/models/camaleon_cms/post_type.rb
app/models/camaleon_cms/term_relationship.rb
app/models/camaleon_cms/term_taxonomy.rb
app/models/camaleon_cms/theme.rb
app/models/camaleon_cms/user_role.rb
app/models/concerns/camaleon_cms/user_methods.rb
lib/camaleon_cms/engine.rb

This change affects rails apps that rely on Rails 5 and 6 standards.
Currently when you design a rails app you expect to have a validation on `belongs_to` relationship. When adding Camaleon CMS you lose this, breaking the original code and it is not possible to override adding the setting back again in an initializers,
Given that this change on rails settings has been implemented for a while and that we should avoid to override rails settings in  a gem I would suggest to remove this line.
Running Camaleon tests it passes and the CMS seems to work fine without this setting.

Removes ability to set belongs_to_required_by_default to false

---

.github/workflows/current_support.yml
.github/workflows/experimental_support.yml
README.md

Travis CI has updated their pricing tiers, and Camaleon no longer seems to be working on the free version.
This PR adds two Github actions workflows to the repo. One runs the tests for all supported versions of Ruby/Rails, and the other one runs tests for upcoming versions. These are separate so that the build for supported versions doesn't fail due to incompatibility with a future version.
I chose Github actions to replace Travis CI because it seems easiest to house the builds with the code. Github Actions doesn't seem to have total feature parity (allowed failures, etc), so if someone feels strongly about using a different tool we can look at that. For now I just want something that will run the tests since Travis stopped working, and GA will at least do that.
The Github actions builds …

Use Github actions for CI build

---

.github/workflows/experimental_support.yml
camaleon_cms.gemspec
spec/support/common.rb

This commit adds a CI job for Ruby 3.1, which was released in preview today. Unfortunately, Github Actions hasn't added Ruby 3.1.0-preview1 yet, so the job doesn't pass CI yet. However, the spec passes locally in Ruby 3.1, and the ruby-head CI job passes as well (for the first time EVER, I think). So we have plenty of evidence that Camaleon will work just fine in Ruby 3.1.
The gems added to the gemspec are dependencies of the Mail gem. Ruby 3.1 still bundles these gems but no longer requires them by default, so for the first time they must be explicitly added. Presumably the Mail gem will receive an update at some point so that Camaleon no longer needs to include these gems in the gemspec.
Lastly, references to a deprecated Selenium exception are updated to get the tests passing.

Ruby 3.1 support

---

.github/workflows/current_support.yml
.github/workflows/experimental_support.yml
Gemfile
app/apps/plugins/attack/config/custom_models.rb
app/apps/plugins/attack/models/attack.rb
app/helpers/camaleon_cms/hooks_helper.rb
camaleon_cms.gemspec
config/initializers/action_view.rb
config/initializers/custom_initializers.rb
config/initializers/model_alias.rb
gemfiles/rails_7_0.gemfile
spec/helpers/email_helper_spec.rb
spec/support/common.rb

This PR adds Rails 7.0 support. Rails 7.0 is still in the alpha release stage, so this shouldn't be merged until there's a release candidate. I'm opening the PR for comments right now. It is built on top of #1010, so that PR should be merged first or closed in favor of this one.
The biggest changes are in some initialization code. Rails 7 changes autoloading behavior on boot, so that's what caused most of the changes to the framework code. There was also a monkey patch for an Action View method that is removed in Rails 7, so that is dealt with as well.
Rails 7.0 is added to the CI build. Since I was adding jobs to the build, I also switched to a matrix approach. Previously, on Travis CI, only four jobs would run concurrently, so it made sense to use fewer jobs in the build. Now with …

Rails 7.0 support

---

.gitignore
config/initializers/assets.rb
spec/dummy/config/environments/test.rb
spec/factories/site.rb
spec/features/admin/posts_spec.rb
spec/features/admin/settings_spec.rb
spec/features/admin/sites_spec.rb
spec/spec_helper.rb
spec/support/webfont_icon_check.rb

To avoid failures when changing something regarding the assets, I have created a method for fetching the asset path from DOM from the font-face, and then making an AJAX request trying to fetch the asset.
Works with FontAwesome and Glyphicons. 
Doesn't work with Tiny MCE webfont because of the same reason as native Bootstrap's Glyphicons - Sprockets doesn't correctly process relative URL paths. We should definitely re-work the bundling system to get rid of Sprockets (Propshaft or Webpack or whatever else).
Also, had to change Site's factory `theme` attribute to a hard-coded `default` string because previously used `PluginRoutes.all_themes.first` has changed ordering in Ruby 3.0, and is returning `camaleon_first` instead of `default`.

Test for asset existence

---

.gitignore
CHANGELOG.md
app/assets/javascripts/camaleon_cms/admin/_custom_fields.js
app/assets/javascripts/camaleon_cms/admin/_data.js
app/assets/javascripts/camaleon_cms/admin/_post.js
app/assets/javascripts/camaleon_cms/admin/_translator.js
app/assets/javascripts/camaleon_cms/admin/tinymce/plugins/filemanager/plugin.min.js
app/assets/stylesheets/camaleon_cms/admin/_custom_admin.css.scss
camaleon_cms.gemspec
config/initializers/assets.rb
spec/features/admin/settings_spec.rb

This PR completes the upgrade of TinyMCE to v5, replacing #1035. It has been rebased on the v3 branch. One last consideration is whether the TinyMCE assets should be copied or compiled. We've switched it a couple of times. This PR chooses the compile option, but only because I did that for some reason when I first tried version 5 in 2020. It can be changed if needed.
For the next upgrade to v6, the tricky part is that the jQuery wrapper was removed from the gem, so we most likely have to change a bunch of code. We had discussed removing jQuery entirely and re-writing the frontend, so I'd like to hear ideas about that before diving into the next step.

TinyMCE version 5

---

.gitignore
.rubocop.yml
SECURITY.md
app/helpers/camaleon_cms/frontend/application_helper.rb
app/helpers/camaleon_cms/frontend/seo_helper.rb
lib/ext/translator.rb
spec/helpers/seo_helper_spec.rb

Currently, the canonical link, when it has different links on different languages, is generating a broken link:
```html
<link rel="canonical" href="[&lt;!--:en--&gt;https://florsan.md/&lt;!--:--&gt;&lt;!--:ru--&gt;https://florsan.md/ru&lt;!--:--&gt;&lt;!--:md--&gt;https://florsan.md/md&lt;!--:--&gt;](view-source:http://0.0.0.0:3000/%3C!--:en--%3Ehttps://florsan.md/%3C!--:--%3E%3C!--:ru--%3Ehttps://florsan.md/ru%3C!--:--%3E%3C!--:md--%3Ehttps://florsan.md/md%3C!--:--%3E)">
```
This PR is fixing it, calling `translate`: `current_site.get_option('seo_canonical')&.translate`
Also, some small performance optimizations were implemented.

Fix seo_canonical option to be translated for the frontend, and some optimizations

---

app/apps/plugins/attack/models/attack.rb
app/models/application_record.rb
app/models/camaleon_cms/category.rb
app/models/camaleon_cms/custom_field.rb
app/models/camaleon_cms/custom_fields_relationship.rb
app/models/camaleon_cms/media.rb
app/models/camaleon_cms/meta.rb
app/models/camaleon_cms/nav_menu.rb
app/models/camaleon_cms/nav_menu_item.rb
app/models/camaleon_cms/plugin.rb
app/models/camaleon_cms/post.rb
app/models/camaleon_cms/post_comment.rb
app/models/camaleon_cms/post_default.rb
app/models/camaleon_cms/post_relationship.rb
app/models/camaleon_cms/post_tag.rb
app/models/camaleon_cms/post_type.rb
app/models/camaleon_cms/site.rb
app/models/camaleon_cms/term_relationship.rb
app/models/camaleon_cms/term_taxonomy.rb
app/models/camaleon_cms/theme.rb
app/models/camaleon_cms/user.rb
app/models/camaleon_cms/user_role.rb
app/models/camaleon_record.rb
app/models/concerns/camaleon_cms/common_relationships.rb
app/models/concerns/camaleon_cms/user_methods.rb
config/initializers/active_record_extension.rb
lib/generators/camaleon_cms/gem_plugin_template/app/models/plugins/my_plugin/my_plugin.rb

- Move common AR methods from ActiveRecord::Base to ApplicationRecord
- AR models now inherit from ApplicationRecord
- Remove cama_attr_changed? method used to detect Rails 4 - as from Rails 6 just use the `ActiveRecord::AttributeMethods::Dirty.saved_change_to_attribute?`
- DRY a bit the PostType and Site models using conditional callbacks
- Refactor the AR class method `cama_define_common_relationships` into the `CommonRelationships` AR Concern included only where it is necessary

Refactor AR models to inherit from ApplicationRecord and extract the CommonRelationships concern

---

app/controllers/camaleon_cms/admin/settings_controller.rb
app/mailers/camaleon_cms/html_mailer.rb

Previously, the test email always sent from the main site even when initiated from a different site.
Fixes #1049

Fix the test email for non-main sites

---

CHANGELOG.md
app/apps/themes/camaleon_first/assets/js/main.js
app/apps/themes/default/assets/js/main.js
app/apps/themes/new/assets/js/main.js
app/assets/javascripts/camaleon_cms/admin/admin-basic-manifest.js
app/assets/javascripts/camaleon_cms/admin/admin-manifest.js
lib/generators/camaleon_cms/theme_template/assets/js/main.js
spec/dummy/app/apps/themes/camaleon_first/assets/js/main.js
spec/dummy/app/apps/themes/default/assets/js/main.js
spec/dummy/app/apps/themes/new/assets/js/main.js

Before working on transition to jQuery 3.xx, which will presumably require additional refactoring work and testing, let's make an easy transition to jQuery 2.xx - actually, the last 2.xx version - the 2.2.4.
Here are some highlights of the changes that jQuery 2.0 brings:
- No more support for IE 6/7/8
- Reduced size: The final 2.0.0 file is 12 percent smaller than the 1.9.1 file, thanks to the elimination of patches that were only needed for IE 6, 7, and 8. 
- jQuery 1.9 API equivalence: jQuery 2.0 is API-compatible with 1.9

Use jQuery 2.x

---

CHANGELOG.md
app/controllers/camaleon_cms/camaleon_controller.rb
lib/ext/string.rb

Starting from Rails 7.0 a redirection to other host will raise an exception unless the `redirect_to` method is called with the `allow_other_host: true` option

On cama_site_check_existence, if site is unknown, allow_other_host: true for redirection to main site

---

.rubocop.yml
app/controllers/camaleon_cms/admin/installers_controller.rb
app/controllers/camaleon_cms/camaleon_controller.rb
app/helpers/camaleon_cms/admin/category_helper.rb
app/helpers/camaleon_cms/frontend/nav_menu_helper.rb
app/helpers/camaleon_cms/html_helper.rb
app/helpers/camaleon_cms/uploader_helper.rb
app/models/camaleon_cms/post.rb
app/uploaders/camaleon_cms_uploader.rb
app/validators/camaleon_cms/post_uniq_validator.rb
app/validators/camaleon_cms/uniq_validator.rb
app/views/camaleon_cms/default_theme/sitemap.xml.builder
config/initializers/custom_initializers.rb
package.json
spec/helpers/uploader_helper_spec.rb

From the MiniMagick 5.0 release notes:
"Removed deprecated Image#mime_type, as it wasn't accurate.
MIME type from file content should be determined either using Marcel or MimeMagic, or mime-types or MiniMime using Image#type."

Use MiniMime for mime types, because the MiniMagick 5.0 has no Image#mime_type

---

.rubocop.yml
CHANGELOG.md
app/models/camaleon_cms/term_taxonomy.rb
spec/models/category_spec.rb
spec/models/nav_menu_item_spec.rb
spec/models/nav_menu_spec.rb
spec/models/plugin_spec.rb
spec/models/post_tag_spec.rb
spec/models/post_type_spec.rb
spec/models/site_spec.rb
spec/models/term_taxonomy_spec.rb
spec/models/theme_spec.rb
spec/models/user_role_spec.rb
spec/models/widget/widget_main_spec.rb
spec/models/widget/widget_sidebar_spec.rb
spec/shared_specs/sanitize_attrs.rb

Fixes reported XSS vulnerability when editing content groups in the admin dashboard.

Sanitize name and description attrs of TermTaxonomy classes to prevent XSS attacks

---

CHANGELOG.md
app/models/camaleon_cms/custom_field_group.rb
app/models/camaleon_cms/post_default.rb
app/models/concerns/camaleon_cms/custom_fields_read.rb

There are several deprecation warnings on CI on Rails 6.1. This PR is fixing the issues.
- In PostDefault: Fix "Deprecate .reorder(nil) with .first / .first! taking non-deterministic result" message - see https://github.com/rails/rails/pull/36889
- in CustomFieldGroup: Fix Deprecation warning in 6.1 if a default_scope contains a where.not - see https://github.com/rails/rails/issues/42759
-  Remove deprecated associations from the custom_fields_read mixin, do some micro-optimizations of the code

Fix ActiveRecord deprecations from Rails 6.1

---

CHANGELOG.md
app/helpers/camaleon_cms/html_helper.rb

Previously, the `colorpicker` asset compilation has been fixed, now fixing for `scss` files to be added to the `styleshhet_link_tag` in `cama_draw_custom_assets`.

Add scss to the styleshhet_link_tag in cama_draw_custom_assets

---

CHANGELOG.md
app/assets/stylesheets/camaleon_cms/admin/admin-manifest.css
app/assets/stylesheets/camaleon_cms/admin/colorpicker.css
app/helpers/camaleon_cms/html_helper.rb

It was just forgotten to be added to `admin-manifest.css`.

Revert previous colorpicker asset related changes and just require it in the admin-manifest.css

---

CHANGELOG.md
app/helpers/camaleon_cms/uploader_helper.rb
app/uploaders/camaleon_cms_uploader.rb
spec/helpers/uploader_helper_spec.rb

Arbitrary file write to RCE (GHSL-2024-182) vulnerability reported:
An arbitrary file write vulnerability accessible via the upload method of the `MediaController` allows authenticated users to write arbitrary files to any location on the web server Camaleon CMS is running on (depending on the permissions of the underlying filesystem). E.g. This can lead to a delayed remote code execution in case an attacker is able to write a Ruby file into the config/initializers/ subfolder of the Ruby on Rails application.
This PR fixes the vulnerability by introducing the `CamaleonCmsUploader.valid_folder_path?` method which checks for directory traversal path, absolute file path, and URI-like path.

Mitigate arbitrary path write in uploader (GHSL-2024-182)

---

CHANGELOG.md
Gemfile
app/controllers/camaleon_cms/admin/media_controller.rb
app/uploaders/camaleon_cms_aws_uploader.rb
app/uploaders/camaleon_cms_local_uploader.rb
spec/dummy/config/environments/test.rb
spec/requests/download_private_file_spec.rb

Arbitrary path traversal in `download_private_file` (GHSL-2024-183) vulnerability reported:
A path traversal vulnerability accessible via MediaController's download_private_file method allows authenticated users to download any file on the web server Camaleon CMS is running on (depending on the file permissions).
This PR fixes the vulnerability by introducing a check in the `CamaleonCmsLocalUploader`'s `fetch_file` method for the filename to not include `..`.
Also, changed the exception-based control flow of the `fetch_file` to just returning errors, because:
- Rails 7.2 changed the behavior to only report errors that are not considered "handled" based on the `ActionDispatch::ExceptionWrapper.rescue_responses` list (see - …

Mitigate arbitrary path traversal in download_private_file  (GHSL-2024-183)

---

CHANGELOG.md
app/helpers/camaleon_cms/uploader_helper.rb
app/uploaders/camaleon_cms_uploader.rb
spec/helpers/uploader_helper_spec.rb
spec/support/fixtures/unsafe-test-xss.svg

Stored XSS through user file upload  (GHSL-2024-184) vulnerability reported:
A stored cross-site scripting has been found in the image upload functionality that can be used by normal registered users: It is possible to upload a SVG image containing JavaScript and it's also possible to upload a HTML document when the format parameter is manually changed to [documents](https://github.com/owen2345/camaleon-cms/blob/feccb96e542319ed608acd3a16fa5d92f13ede67/app/uploaders/camaleon_cms_uploader.rb#L105-L106) or a string of an [unsupported format](https://github.com/owen2345/camaleon-cms/blob/feccb96e542319ed608acd3a16fa5d92f13ede67/app/uploaders/camaleon_cms_uploader.rb#L110-L111). If an authenticated user or administrator visits …

Mitigate stored XSS through user file upload (GHSL-2024-184)

---

CHANGELOG.md
app/controllers/camaleon_cms/admin/media_controller.rb
app/uploaders/camaleon_cms_local_uploader.rb
spec/uploaders/local_uploader_spec.rb

Arbitrary file delete in `MediaController#delete_file` (GHSL-2024-186) vulnerability reported:
"The `actions` method, defined inside of the MediaController class, doesn't check whether a given path is inside a certain path (e.g. inside the media folder). If an attacker performed an account takeover of an administrator account (See: GHSL-2024-184) they could delete arbitrary files or folders on the server hosting Camaleon CMS".
The report, though, isn't accurate, because the `@current_site.upload_directory` folder is prefixing the folder or file name to delete in the  `delete_folder` and `delete_file` methods. What's missing, is a traversal check.
This PR fixes the vulnerability by introducing a check for path traversal check …

Mitigate Arbitrary file delete vulnerability (GHSL-2024-186)

---

CHANGELOG.md
app/models/camaleon_cms/custom_field_group.rb
app/views/camaleon_cms/admin/settings/custom_fields/_get_items.html.erb
app/views/camaleon_cms/admin/settings/custom_fields/_render.html.erb

Remote code execution through code injection (GHSL-2024-185) vulnerability reported:
"The pages rendering custom fields contain a hidden feature called label evaluation, that can be enabled when creating custom field groups. If an attacker performed an account takeover of an administrator account (See: GHSL-2024-184) they can execute arbitrary Ruby code on the server hosting Camaleon CMS.
If the (hidden) custom field option label_eval was set when creating the custom field form, the text of the label is evaluated when it's rendered."
This PR fixes the vulnerability by removing the hidden `label_eval` field and removing the calls to `eval` the `field.name` and `field.description`.

Mitigate remote code execution through code injection (GHSL-2024-185)

---

CHANGELOG.md
app/models/camaleon_cms/term_taxonomy.rb
spec/shared_specs/sanitize_attrs.rb

Sanitization of the `TermTaxonomy` attributes were surprizingly removing translation tags.
So, instead of a `VineyardsВиноградникиPodgorii` attr value, the `VineyardsВиноградникиPodgorii` was stored into the DB.
This PR fixes the issue, hiding the translation tags before sanitizing them, and restoring them afterwards.

Fix TermTaxonomy attributes sanitizing to not remove translation tags

---

lib/plugin_routes.rb

Ruby 3.4 issues deprecation warnings when mutating strings in a file that does not have a `frozen_string_literal: false` comment. When testing my app locally with Ruby 3.4, there are deprecation warnings because plugin_routes.rb uses mutated strings.
This PR adds a magic comment to that file to silence the deprecation warnings and to ensure that the current behavior will continue even after a future version of Ruby freezes strings by default.

Add magic comment to use mutable strings

---

app/helpers/camaleon_cms/uploader_helper.rb

Fixes #1106 
This is based on [an earlier version](https://github.com/owen2345/camaleon-cms/commit/cad7c8e3e2a7623cafd42410045b61fe0907c8ac) of @texpert 's work. I did not alter the list of attributes screened for in that work, I just reimplemented them to address the issue above caused by the more general regexp.

Address false positives on malicious upload check

---

app/models/concerns/camaleon_cms/custom_fields_read.rb
app/models/concerns/camaleon_cms/metas.rb
lib/ext/string.rb

JSON.fast_generate will be removed in version 3 of the json gem.

Remove deprecated method
